name: CI - Healthcheck

on:
  pull_request:
    branches:
      - main

jobs:
  healthcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t f1-api:ci .

      - name: Run container
        run: |
          docker run -d \
            -p 3000:3000 \
            -e PORT=3000 \
            --name f1-api-ci \
            f1-api:ci

      - name: Wait for API to be ready
        run: sleep 5

      - name: Healthcheck
        run: |
          curl -f http://localhost:3000/health

      - name: Stop container
        if: always()
        run: docker rm -f f1-api-ci
